config/routes.rb
Aggrate::Application.routes.draw do

  resources :google_posts

  resources :users

  resources :tweets

  controller :home do
    get 'index' => :index
  end

  controller :admin do
    get 'admin' => 'admin#index', :as => :admin
  end

  controller :session do
    get   'login'     => :new,      :as => :login
    post  'login/go'  => :create,   :as => :login_go
    get   'logout'    => :destroy,  :as => :logout
  end

  resources :feeds

  root :to => 'home#index'

end

app/models/feed.rb
class Feed < ActiveRecord::Base

  has_many    :entries, :as => :source, :dependent => :destroy

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

  layout 'admin'
  
  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feeds }
    end
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
    @feed = Feed.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feed }
    end
  end

  # GET /feeds/new
  # GET /feeds/new.json
  def new
    @feed = Feed.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feed }
    end
  end

  # GET /feeds/1/edit
  def edit
    @feed = Feed.find(params[:id])
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(params[:feed])

    respond_to do |format|
      if @feed.save
        format.html { redirect_to feeds_url, notice: 'Feed was successfully created.' }
        format.json { render json: @feed, status: :created, location: @feed }
      else
        format.html { render action: "new" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feeds/1
  # PUT /feeds/1.json
  def update
    @feed = Feed.find(params[:id])

    respond_to do |format|
      if @feed.update_attributes(params[:feed])
        format.html { redirect_to feeds_url, notice: 'Feed was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy

    respond_to do |format|
      format.html { redirect_to feeds_url }
      format.json { head :ok }
    end
  end
end

app/views/feeds/_form.html.haml
= form_for @feed do |f|
  -if @feed.errors.any?
    #error_explanation
      %h2= "#{pluralize(@feed.errors.count, "error")} prohibited this feed from being saved:"
      %ul
        - @feed.errors.full_messages.each do |msg|
          %li= msg

  .clearfix
    = f.label :link
    .input= f.text_field :link
  .clearfix
    = f.label :title
    .input= f.text_field :title
  .clearfix
    = f.label :homepage
    .input= f.text_field :homepage
  .actions
    = f.submit 'Save', :class => 'btn success'
    = link_to 'Cancel', feeds_path, :class => 'btn'

app/views/feeds/edit.html.haml
%h1 Editing Feed

= render 'form'

app/views/feeds/index.html.haml
%h1 Feeds

%table
  %tr
    %th Title
    %th Link
    %th Homepage
    %th Last checked
    %th
    %th
    %th

  - @feeds.each do |feed|
    %tr
      %td= link_to truncate(feed.title, :length => 40), feed.homepage
      %td= link_to truncate(feed.link, :length => 40), feed.link
      %td= link_to truncate(feed.homepage, :length => 40), feed.homepage
      %td= time_ago_in_words(feed.last_checked_at) + ' ago' if feed.last_checked_at
      %td= error_note(feed)
      %td= link_to 'Edit', edit_feed_path(feed)
      %td= link_to 'Destroy', feed, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Feed', new_feed_path, :class => 'btn success'

app/views/feeds/new.html.haml
%h1 New Feed

= render 'form'