config/routes.rb
Aggrate::Application.routes.draw do

  resources :google_posts

  resources :users

  resources :tweets

  controller :home do
    get 'index' => :index
  end

  controller :admin do
    get 'admin' => 'admin#index', :as => :admin
  end

  controller :session do
    get   'login'     => :new,      :as => :login
    post  'login/go'  => :create,   :as => :login_go
    get   'logout'    => :destroy,  :as => :logout
  end

  resources :feeds

  root :to => 'home#index'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base

  scope :accounts, where("username != ''")
  scope :searches, where("search_term != ''")
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  layout 'admin'
  
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/new
  # GET /tweets/new.json
  def new
    @tweet = Tweet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(params[:tweet])

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_url, notice: 'Tweet was successfully created.' }
        format.json { render json: @tweet, status: :created, location: @tweet }
      else
        format.html { render action: "new" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tweets/1
  # PUT /tweets/1.json
  def update
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      if @tweet.update_attributes(params[:tweet])
        format.html { redirect_to tweets_url, notice: 'Tweet was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :ok }
    end
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.haml
= form_for @tweet do |f|
  -if @tweet.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tweet.errors.count, "error")} prohibited this tweet from being saved:"
      %ul
        - @tweet.errors.full_messages.each do |msg|
          %li= msg

  .clearfix
    = f.label :username
    .input= f.text_field :username
  .clearfix
    = f.label :search_term
    .input= f.text_field :search_term
  .actions
    = f.submit 'Save', :class => 'btn success'
    = link_to 'Cancel', tweets_path, :class => 'btn'

app/views/tweets/edit.html.haml
%h1 Editing Twitter Search

= render 'form'

app/views/tweets/index.html.haml
%h1 Twitter Searches

%table
  %tr
    %th Username
    %th Search term
    %th Last checked
    %th
    %th
    %th

  - @tweets.each do |tweet|
    %tr
      %td= tweet.username
      %td= tweet.search_term
      %td= time_ago_in_words(tweet.last_checked_at) + ' ago' if tweet.last_checked_at
      %td= error_note(tweet)
      %td= link_to 'Edit', edit_tweet_path(tweet)
      %td= link_to 'Destroy', tweet, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Search', new_tweet_path, :class => 'btn success'

app/views/tweets/new.html.haml
%h1 New Twitter Search

= render 'form'