config/routes.rb
Aggrate::Application.routes.draw do

  resources :google_posts

  resources :users

  resources :tweets

  controller :home do
    get 'index' => :index
  end

  controller :admin do
    get 'admin' => 'admin#index', :as => :admin
  end

  controller :session do
    get   'login'     => :new,      :as => :login
    post  'login/go'  => :create,   :as => :login_go
    get   'logout'    => :destroy,  :as => :logout
  end

  resources :feeds

  root :to => 'home#index'

end

app/models/google_post.rb
class GooglePost < ActiveRecord::Base

  scope :accounts, where("user_id != ''")
  scope :searches, where("search_term != ''")

end

app/controllers/google_posts_controller.rb
class GooglePostsController < ApplicationController

  layout 'admin'
  
  # GET /google_posts
  # GET /google_posts.json
  def index
    @google_posts = GooglePost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @google_posts }
    end
  end

  # GET /google_posts/1
  # GET /google_posts/1.json
  def show
    @google_post = GooglePost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @google_post }
    end
  end

  # GET /google_posts/new
  # GET /google_posts/new.json
  def new
    @google_post = GooglePost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @google_post }
    end
  end

  # GET /google_posts/1/edit
  def edit
    @google_post = GooglePost.find(params[:id])
  end

  # POST /google_posts
  # POST /google_posts.json
  def create
    @google_post = GooglePost.new(params[:google_post])

    respond_to do |format|
      if @google_post.save
        format.html { redirect_to google_posts_url, notice: 'Google post was successfully created.' }
        format.json { render json: @google_post, status: :created, location: @google_post }
      else
        format.html { render action: "new" }
        format.json { render json: @google_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /google_posts/1
  # PUT /google_posts/1.json
  def update
    @google_post = GooglePost.find(params[:id])

    respond_to do |format|
      if @google_post.update_attributes(params[:google_post])
        format.html { redirect_to google_posts_url, notice: 'Google post was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @google_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /google_posts/1
  # DELETE /google_posts/1.json
  def destroy
    @google_post = GooglePost.find(params[:id])
    @google_post.destroy

    respond_to do |format|
      format.html { redirect_to google_posts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/google_posts_helper.rb
module GooglePostsHelper
end

app/views/google_posts/_form.html.haml
= form_for @google_post do |f|
  -if @google_post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@google_post.errors.count, "error")} prohibited this google_post from being saved:"
      %ul
        - @google_post.errors.full_messages.each do |msg|
          %li= msg

  .clearfix
    = f.label :user_id
    .input= f.text_field :user_id
  .clearfix
    = f.label :username
    .input= f.text_field :username
  .clearfix
    = f.label :search_term
    .input= f.text_field :search_term
  .actions
    = f.submit 'Save', :class => 'btn success'
    = link_to 'Cancel', google_posts_path, :class => 'btn'

app/views/google_posts/edit.html.haml
%h1 Editing google_post

= render 'form'

= link_to 'Show', @google_post
\|
= link_to 'Back', google_posts_path

app/views/google_posts/index.html.haml
%h1 Google+ Searches

%table
  %tr
    %th User ID
    %th Username
    %th Search term
    %th Last checked at
    %th 
    %th
    %th

  - @google_posts.each do |google_post|
    %tr
      %td= google_post.user_id
      %td= google_post.username
      %td= google_post.search_term
      %td= time_ago_in_words(google_post.last_checked_at) + ' ago' if google_post.last_checked_at
      %td= error_note(google_post)
      %td= link_to 'Edit', edit_google_post_path(google_post)
      %td= link_to 'Destroy', google_post, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Google+ Search', new_google_post_path, :class => 'btn success'

app/views/google_posts/new.html.haml
%h1 New google_post

= render 'form'

= link_to 'Back', google_posts_path