config/routes.rb
Aggrate::Application.routes.draw do

  resources :google_posts

  resources :users

  resources :tweets

  controller :home do
    get 'index' => :index
  end

  controller :admin do
    get 'admin' => 'admin#index', :as => :admin
  end

  controller :session do
    get   'login'     => :new,      :as => :login
    post  'login/go'  => :create,   :as => :login_go
    get   'logout'    => :destroy,  :as => :logout
  end

  resources :feeds

  root :to => 'home#index'

end

app/views/layouts/_admin_nav.html.haml
.topbar-wrapper(style="z-index: 5;")
  .topbar(data-dropdown="dropdown")
    .topbar-inner
      .container
        %h3= link_to 'Aggrate', root_path
        %ul.nav
          %li= link_to 'Dashboard', admin_path
          %li= link_to 'Users', users_path
          %li.dropdown
            = link_to 'Sources', '#', :class => "dropdown-toggle"
            %ul.dropdown-menu
              %li= link_to 'Email', '#'
              %li= link_to 'Google+', google_posts_path
              %li= link_to 'RSS Feeds', feeds_path
              %li= link_to 'Twitter', tweets_path
        %ul.nav.secondary-nav
          %li= link_to 'Logout', logout_path

app/views/layouts/admin.html.haml
!!! 5
%html
  %head
    %title Aggrate
    = stylesheet_link_tag    'application', 'admin'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render 'layouts/admin_nav' if logged_in?

    .container
      - if flash[:notice]
        .alert-message.success
          = link_to '×', '#', :class => 'close'
          %p= flash[:notice]
        :javascript
          $(".alert-message").alert();

      = yield

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Feeds for Woodworkers
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta(name="description" content="Pulling together the latest in woodworking blogs, tweets, google+, email newsletters and more...")
    %meta(name="keywords" content="woodworking,rss,feeds,aggregate,blogs,twitter,google+,email,newsletters")

  %body
    - if logged_in?
      = render 'layouts/admin_nav'
      
    .container
      .hero-unit
        %h1 Feeds for Woodworkers
        %p Pulling together the latest in woodworking blogs, tweets, newsletters and more...
      = yield

    %footer.footer
      .container
        %p 
          Part of the 
          %strong= link_to 'For Woodworkers Network', 'http://forwoodworkers.com'
          &copy;#{Time.now.year}. Another awesome site brought to you by 
          %strong= link_to 'Rob Cameron', 'http://ridingtheclutch.com'